services:
    postgres:
        image: postgres:16-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    typesense:
        image: typesense/typesense:26.0
        restart: on-failure
        ports:
            - "8108:8108"
        command: "--api-key=admin --data-dir=/data --enable-cors"
        volumes:
            - typesense-data:/data
    mongo:
        image: mongo
        restart: on-failure
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:7-alpine
        restart: on-failure
        ports:
            - "6379:6379"

volumes:
    postgres-data:
    typesense-data:
    mongo-data:
