services:
    postgres:
        image: postgres:16-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    typesense:
        image: typesense/typesense:26.0
        restart: on-failure
        ports:
            - "8108:8108"
        command: "--api-key=admin --data-dir=/data --enable-cors"
        volumes:
            - typesense-data:/data

    mongo:
        image: mongo
        restart: on-failure
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:7-alpine
        restart: on-failure
        ports:
            - "6379:6379"

    gorse:
        image: zhenghaoz/gorse-in-one:0.4
        restart: unless-stopped
        ports:
            - 8088:8088
        environment:
            GORSE_CACHE_STORE: redis://redis:6379
            # I would like to use PostgreSQL as the primary store, but it forces SSL.
            GORSE_DATA_STORE: mongodb://mongo:27017/gorse
        command: >
            -c /etc/gorse/config.toml  --log-path /var/log/gorse/master.log  --cache-path
            /var/lib/gorse/master_cache.data
        volumes:
            - ./config/gorse.dev.toml:/etc/gorse/config.toml
        depends_on:
            - redis
            - mongo

volumes:
    postgres-data:
    typesense-data:
    mongo-data:
